name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Clean old node_modules
      run: rm -rf node_modules .prisma

    - name: Install dependencies
      run: npm ci

    - name: Generate Prisma Client
      run: npx prisma generate

    - name: Setup .env
      run: |
        touch .env
        echo "${{ secrets.ENV_PROD }}" > .env

    - name: Build the app
      run: npm run build

    - name: Restart with PM2
      run: pm2 restart nestJs-api-backend
